/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.AbsenceController;
import Controllers.UserController;
import Models.Absences;
import Models.Personne;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/**
 *
 * @author mabro
 */
public class EtudiantFrameAbsences extends javax.swing.JFrame {

    DefaultTableModel model;
    /**
     * Creates new form EtudiantFrameAbsences
     */
    public EtudiantFrameAbsences() {
        initComponents();
        LoadJtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        AbsBtn = new javax.swing.JButton();
        NotesBtn = new javax.swing.JButton();
        MoyBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 35, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(242, 242, 242));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AbsBtn.setBackground(new java.awt.Color(23, 35, 51));
        AbsBtn.setForeground(new java.awt.Color(242, 242, 242));
        AbsBtn.setText("Absences");
        AbsBtn.setBorder(null);
        AbsBtn.setBorderPainted(false);
        AbsBtn.setContentAreaFilled(false);
        AbsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbsBtnMouseClicked(evt);
            }
        });

        NotesBtn.setBackground(new java.awt.Color(23, 35, 51));
        NotesBtn.setForeground(new java.awt.Color(242, 242, 242));
        NotesBtn.setText("Notes");
        NotesBtn.setBorder(null);
        NotesBtn.setBorderPainted(false);
        NotesBtn.setContentAreaFilled(false);
        NotesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotesBtnMouseClicked(evt);
            }
        });

        MoyBtn.setBackground(new java.awt.Color(23, 35, 51));
        MoyBtn.setForeground(new java.awt.Color(242, 242, 242));
        MoyBtn.setText("Moyenne");
        MoyBtn.setBorder(null);
        MoyBtn.setContentAreaFilled(false);
        MoyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoyBtnMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(23, 35, 51));
        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(23, 35, 51));
        jTable1.setForeground(new java.awt.Color(242, 242, 242));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AbsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(NotesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MoyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(NotesBtn)
                .addGap(112, 112, 112)
                .addComponent(AbsBtn)
                .addGap(100, 100, 100)
                .addComponent(MoyBtn)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void LoadJtable()   {
        jTable1.clearSelection();
        try {
            UserController userController = new UserController();
            List<Personne> personnes = new ArrayList<>();
            personnes = userController.getAllPersonne();
            AbsenceController absenceController = new AbsenceController();
            List<Absences> absences = new ArrayList<>();
            File file = new File("logfile.txt");
            Scanner reader = new Scanner(file);
            model = (DefaultTableModel) jTable1.getModel();
            Object[] rowData = new Object[20];

            for (Personne p: personnes) {
                System.out.println(p.getMail());
                String mail = reader.nextLine();
                System.out.println("reader Line : " + mail);
                if(p.getMail().equalsIgnoreCase(mail)) {
                        System.out.println("im here");
                        absences = absenceController.getAbsenceByEtudiant(p.getCin());
                        for (int j = 0; j < absences.size(); j++) {
                            System.out.println("im here");
                            rowData[0] = absences.get(j).getIdEtudiant();
                            rowData[1] = p.getNom();
                            rowData[2] = p.getPrenom();
                            rowData[3] = absences.get(j).getMatiere();
                            rowData[4] = absences.get(j).getNbAbsences();
                            model.addRow(rowData);
                        }
                        break ;

                }else{
                    System.out.println("im not here");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }
    private void AbsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbsBtnMouseClicked
        EtudiantFrameAbsences EFN =  new EtudiantFrameAbsences();
        EFN.pack();
        EFN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AbsBtnMouseClicked

    private void NotesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotesBtnMouseClicked
        EtudiantFrameNote EFN =  new EtudiantFrameNote();
        EFN.pack();
        EFN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NotesBtnMouseClicked

    private void MoyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoyBtnMouseClicked
        EtudiantFrameMoyenne EFN =  new EtudiantFrameMoyenne();
        EFN.pack();
        EFN.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MoyBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtudiantFrameAbsences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtudiantFrameAbsences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtudiantFrameAbsences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtudiantFrameAbsences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtudiantFrameAbsences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbsBtn;
    private javax.swing.JButton MoyBtn;
    private javax.swing.JButton NotesBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
